- hyperlink: https://www.w3schools.com/w3css/default.asp
  image:
  description: W3.CSS

- hyperlink: https://jekyllrb.com
  image:
  description: Jekyll

- hyperlink:
  image:
  description: Liquid

- hyperlink: https://creativecommons.org
  image:
  description: Creative Commons